# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [14]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [15]:
np.__version__

np.show_config()

{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30159",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.12",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30159",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.28",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-uz4hj350/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib direct

C:\Users\Sandriko\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


#### 3. Create a null vector of size 10 (★☆☆)

In [16]:
null_vector = np.zeros(10)

a = np.array([1],dtype='int8')

#### 4. How to find the memory size of any array (★☆☆)

In [17]:
# Memory size of just the array 
null_vector.size * null_vector.itemsize

# Total Memory (array setup + array)
null_vector.__sizeof__()

192

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [18]:
#print(np.add.__doc__)

!python -c "import numpy as np; np.info(np.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [19]:
nulls = np.zeros(10)
nulls[4] = 1

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [20]:
nums = np.arange(10,50)

print(nums)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [21]:
reversed_nums = nums[::-1]

print(reversed_nums)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [22]:
matrix = np.arange(0,9).reshape((3,3))
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [23]:
arr = np.array([1,2,0,0,4,0])

# 0,1,4
indices = np.where(arr != 0)
print(indices)


(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [24]:
'''
[1 0 0
 0 1 0
 0 0 1]
'''
identity_matrix = np.identity(3)

print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [25]:
randos = np.random.random((3,3,3))

print(randos)

[[[0.2890813  0.99608402 0.55395528]
  [0.31659489 0.34902162 0.93857816]
  [0.69856043 0.59999985 0.24078648]]

 [[0.30463411 0.55338645 0.53048978]
  [0.24148034 0.84854119 0.62505727]
  [0.02900265 0.59091296 0.42380445]]

 [[0.37270065 0.35633244 0.69187153]
  [0.79826641 0.1356719  0.04500312]
  [0.6623539  0.31157814 0.24431485]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [26]:
randints = np.random.randint(0,50, (10,10), )

randints.max()
randints.min()

np.int32(0)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [27]:
arr30 = np.random.random(30)

arr30.mean()

np.float64(0.5524424635613737)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [28]:
'''
[1 1 1
 1 0 1
 1 1 1]
'''
size = 5
ones = np.ones((size,size))
zeros = np.zeros((size-2, size-2))

ones[1:len(ones)-1, 1:len(ones)-1] = zeros

ones

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [29]:
arr = np.array([1,2,3])
zeros = np.zeros((3,len(arr)+2))
zeros[1,1:-1] = arr


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [30]:
# 
# nan
# False
# False
# nan
# True
# False
# 

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [31]:
matrix = np.zeros((5,5))
arr = np.arange(1,5)

matrix[arr,arr-1] = arr

matrix

Z = np.diag(np.arange(1,5),k=-1)

Z



array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [32]:
checkerboard = np.zeros((8,8))

checkerboard[::2, 1::2] = 1
checkerboard[1::2, ::2] = 1 

checkerboard

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [33]:
arr = np.arange(0,6*7*8).reshape((6,7,8))

arr[1,5,3] 

print(np.unravel_index(99,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [34]:
arr = np.array([0,1])

odd_row = np.tile(arr, 4)
even_row = np.tile(arr[::-1], 4)

print(np.hstack((odd_row,even_row)))

np.tile(np.hstack((odd_row,even_row)),4).reshape((8,8))


[0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0]


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [35]:
np.random.seed(42)

mat = np.random.randint(0,10,(5,5))

print(mat / np.linalg.det(mat))

(mat - mat.mean()) / mat.std()


[[0.00338983 0.00169492 0.0039548  0.00225989 0.00338983]
 [0.00508475 0.00112994 0.00338983 0.0039548  0.00225989]
 [0.00169492 0.0039548  0.0039548  0.00112994 0.00282486]
 [0.00225989 0.00056497 0.0039548  0.00282486 0.00056497]
 [0.00225989 0.         0.00508475 0.00282486 0.00451977]]


array([[ 0.45626575, -0.76587466,  0.86364589, -0.35849452,  0.45626575],
       [ 1.67840617, -1.1732548 ,  0.45626575,  0.86364589, -0.35849452],
       [-0.76587466,  0.86364589,  0.86364589, -1.1732548 ,  0.04888562],
       [-0.35849452, -1.58063493,  0.86364589,  0.04888562, -1.58063493],
       [-0.35849452, -1.98801507,  1.67840617,  0.04888562,  1.27102603]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [36]:
RGBA = np.dtype('u4')



#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [37]:
a = np.ones((5,3))
b = np.ones((3,2))

c = np.matmul(a,b)


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [38]:
np.random.seed(42)

arr = np.random.randint(0,15,10)

arr

neg_arr = np.where((arr>=3)&(arr<=8),arr.__neg__(),arr)


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [39]:
# 9
# 10



In [40]:
np.random.seed(42)
Z = np.random.randint(0,10,5)

print(Z)

# 2 << Z >> 2 (bitwise shift operator)
# 00000010 --> 100000000

# Z<Z>Z





[6 3 7 4 6]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [41]:
'''
nan
0
[0.0]
'''
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


C:\Users\Sandriko\AppData\Local\Temp\ipykernel_14544\7856763.py:6: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Sandriko\AppData\Local\Temp\ipykernel_14544\7856763.py:7: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\Sandriko\AppData\Local\Temp\ipykernel_14544\7856763.py:8: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [42]:
arr = np.random.random(5)

np.ceil(arr)



array([1., 1., 1., 1., 1.])

#### 30. How to find common values between two arrays? (★☆☆)

In [43]:
a = np.arange(0,10)
b = np.arange(5,10)

np.intersect1d(a,b)


array([5, 6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [44]:
# np.seterr(all='ignore')

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [45]:
np.sqrt(-1) == np.emath.sqrt(-1)

val = np.emath.sqrt(-1)

type(val)

C:\Users\Sandriko\AppData\Local\Temp\ipykernel_14544\632064022.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


numpy.complex128

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [46]:
# from datetime import datetime,timedelta

# today = datetime.now()
# print(today)

# yesterday = today - timedelta(days=1)
# print(yesterday)

# tomorrow = today + timedelta(days=1)
# print(tomorrow)

today = np.datetime64('today')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1,'D')

print(yesterday)
print(tomorrow)




2025-05-14
2025-05-16


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [47]:
july2016 = np.datetime64('2016-07')

np.arange(np.datetime64('2016-07-01'), np.datetime64('2016-08-01'))



array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [48]:
A = np.array([1,2,3,4], dtype='float64')
B = np.array([1,1,1,1], dtype='float64')

np.multiply(np.add(A,B,out=B), np.divide(np.negative(A,out=A),2,out=A),out=A)





array([ -1.,  -3.,  -6., -10.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [49]:
np.random.seed(4)

arr = np.random.random(10)*5

print(arr)

# Method 1
print(arr // 1)

# Method 2
print(np.floor(arr))

# Method 3
print(np.ceil(arr)-1)

# Method 4
arr.astype('int8')



[4.8351492  2.73616125 4.8634218  3.57407997 3.48864412 1.08044748
 4.88137227 0.03115128 1.26491181 2.17395766]
[4. 2. 4. 3. 3. 1. 4. 0. 1. 2.]
[4. 2. 4. 3. 3. 1. 4. 0. 1. 2.]
[4. 2. 4. 3. 3. 1. 4. 0. 1. 2.]


array([4, 2, 4, 3, 3, 1, 4, 0, 1, 2], dtype=int8)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [50]:
matrix = np.tile(np.arange(5),5).reshape((5,5))

matrix

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [51]:
np.random.randint(0,100,10)

array([50, 44, 38, 52,  3,  0, 55, 21, 21, 73], dtype=int32)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [52]:
np.linspace(0,1,11,endpoint=False)[1:]


array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [53]:
a = np.random.random(10)

print(a)

print(np.sort(a))
print(a)

[0.0089861  0.38657128 0.04416006 0.95665297 0.43614665 0.94897731
 0.78630599 0.8662893  0.17316542 0.07494859]
[0.0089861  0.04416006 0.07494859 0.17316542 0.38657128 0.43614665
 0.78630599 0.8662893  0.94897731 0.95665297]
[0.0089861  0.38657128 0.04416006 0.95665297 0.43614665 0.94897731
 0.78630599 0.8662893  0.17316542 0.07494859]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [54]:
a = np.array([1,2,3,4])

np.add.reduce(a)

np.int64(10)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [55]:
A = np.array([1,2,3,8])
B = np.array([1,2,3,3.0])

bool(np.all(A==B))

# Given solution
np.allclose(A,B,atol=0)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [56]:
immutable_array = np.array([1, 2, 3, 4])
immutable_array.flags.writeable = False


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [57]:
np.random.seed(42)

arr = np.random.randint(0,10,(10,2))

print(arr)
'''
(x**2 + y**2)**(1/2) = r
arctan(y/x) = theta
'''
r = np.sqrt(np.sum(np.power(arr, 2),axis=1))
theta = np.arctan(arr[:,1]/arr[:,0])

polar_coords = np.column_stack((r, theta))
polar_coords

[[6 3]
 [7 4]
 [6 9]
 [2 6]
 [7 4]
 [3 7]
 [7 2]
 [5 4]
 [1 7]
 [5 1]]


array([[ 6.70820393,  0.46364761],
       [ 8.06225775,  0.51914611],
       [10.81665383,  0.98279372],
       [ 6.32455532,  1.24904577],
       [ 8.06225775,  0.51914611],
       [ 7.61577311,  1.16590454],
       [ 7.28010989,  0.27829966],
       [ 6.40312424,  0.67474094],
       [ 7.07106781,  1.42889927],
       [ 5.09901951,  0.19739556]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [58]:
arr = np.ones(10)
arr[5] = 100
arr[2] = 100

# If only one instance
# arr[arr.argmax()] = 0

# If multiple equal max values
arr = np.where(arr==arr.max(),0,arr)

arr

array([1., 1., 0., 1., 1., 0., 1., 1., 1., 1.])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [59]:
np.random.random((100,2))

Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))



#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [60]:
X = np.array([1,2,3,4])
Y = np.array([8,9])

C = np.zeros((len(Y),len(X)))

for i in range(len(X)):
    for j in range(len(Y)):
        C[j,i] = 1 / (X[i]-Y[j])



#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [61]:
# Integer types
for dtype in [np.int8, np.int16, np.int32, np.int64, np.uint8, np.uint16, np.uint32, np.uint64]:
    print(f"{dtype}: min={np.iinfo(dtype).min}, max={np.iinfo(dtype).max}")

# Floating-point types
for dtype in [np.float16, np.float32, np.float64]:
    print(f"{dtype}: min={np.finfo(dtype).min}, max={np.finfo(dtype).max}")

<class 'numpy.int8'>: min=-128, max=127
<class 'numpy.int16'>: min=-32768, max=32767
<class 'numpy.int32'>: min=-2147483648, max=2147483647
<class 'numpy.int64'>: min=-9223372036854775808, max=9223372036854775807
<class 'numpy.uint8'>: min=0, max=255
<class 'numpy.uint16'>: min=0, max=65535
<class 'numpy.uint32'>: min=0, max=4294967295
<class 'numpy.uint64'>: min=0, max=18446744073709551615
<class 'numpy.float16'>: min=-65504.0, max=65504.0
<class 'numpy.float32'>: min=-3.4028234663852886e+38, max=3.4028234663852886e+38
<class 'numpy.float64'>: min=-1.7976931348623157e+308, max=1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [62]:
a = np.arange(10000)
print(list(a))

print(np.set_printoptions.__doc__)

[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54), np.int64(55), np.int64(56), np.int64(57), np.int64(58), np.int64(59), np.int64(60), np.int64(61), np.int64(62), np.int64(63), np.int64(64), np.int64(65), np.int64(66), np.int64(67), np.int64(68), np.int64(69), np.int64(70), np.int64(71), n

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [63]:
arr = np.random.randint(0,100,100)
scalar = 5.75

arr[np.argmin(np.abs(scalar - arr))]



np.int32(6)